{% set name = "pyautogen" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: 4a79bab9a78df623caff7bbe5596faa95789fd4c42283a8f7cb36cc1ef5a732e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - httpx >=0.28.1,<1
    - fast-depends >=2.4.12,<3
    - asyncer ==0.0.8
    - websockets >=14,<15
    - python >={{ python_min }},<3.13
    - openai >=1.58
    - diskcache
    - termcolor
    - flaml
    - numpy
    - python-dotenv
    - tiktoken
    - pydantic >=2.6.1,<3
    - docker-py
    - packaging

test:
  imports:
    - autogen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ag2ai/ag2
  summary: A programming framework for agentic AI
  license: Apache-2.0
  license_file:
    - NOTICE.md
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
