{% set name = "pyautogen" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: d1f6ef2ab3df63fc0a12d5130a7c9a1de6af20d0c8d173622a648b29769afe06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - asyncer >=0.0.8
    - websockets >=14,<15
    - python >=3.8,<3.13
    - openai >=1.57
    - diskcache
    - termcolor
    - flaml
    - numpy >=1.17.0,<2
    - python-dotenv
    - tiktoken
    - pydantic >=1.10,<3,!=2.6.0
    - docker-py
    - packaging

test:
  imports:
    - autogen
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/microsoft/autogen
  summary: Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
