{% set name = "pyautogen" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: 4256db19558639e7a28bdc72a56d7c88df1c3b158229b31e31222c721bab2b0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - asyncer >=0.0.8
    - websockets >=14,<15
    - python >={{ python_min }},<3.13
    - openai >=1.58
    - diskcache
    - termcolor
    - flaml
    - numpy >=1.24.0,<2.0.0
    - python-dotenv
    - tiktoken
    - pydantic >=1.10,<3,!=2.6.0
    - docker-py
    - packaging

test:
  imports:
    - autogen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/autogen
  summary: Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
