{% set name = "pyautogen" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: fff693ba174d3ea44ec5667e03913b01e12c6a6a6bb7006b3c851ab360fc0d09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - anyio >=3.0.0,<5.0.0
    - httpx >=0.28.1,<1
    - fast-depends >=2.4.12,<3
    - asyncer ==0.0.8
    - websockets >=14,<15
    - python >={{ python_min }},<3.13
    - openai >=1.58
    - diskcache
    - termcolor
    - flaml
    - numpy
    - python-dotenv
    - tiktoken
    - pydantic >=2.6.1,<3
    - docker-py
    - packaging

test:
  imports:
    - autogen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ag2ai/ag2
  summary: A programming framework for agentic AI
  license: Apache-2.0
  license_file:
    - NOTICE.md
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
