{% set name = "pyautogen" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: ebd2f0fda636783422b4d5c449c447969a2f2bd34d82dcccb7633e2ba3ca0925

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - python >=3.8,<3.13
    - openai >=1.3
    - diskcache
    - termcolor
    - flaml
    - numpy >=1.17.0,<2
    - python-dotenv
    - tiktoken
    - pydantic >=1.10,<3,!=2.6.0
    - docker-py
    - packaging

test:
  imports:
    - autogen
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/microsoft/autogen
  summary: Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
