{% set name = "pyautogen" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyautogen-{{ version }}.tar.gz
  sha256: 38bd96d0984910a4bda05a444452e525137ec1e43060c938a588fe10f3860f51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - fast-depends >=2.4.12,<3
    - asyncer ==0.0.8
    - websockets >=14,<15
    - python >={{ python_min }},<3.13
    - openai >=1.58
    - diskcache
    - termcolor
    - flaml
    - numpy >=1.24.0,<2.0.0
    - python-dotenv
    - tiktoken
    - pydantic >=1.10,<3,!=2.6.0
    - docker-py
    - packaging

test:
  imports:
    - autogen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ag2ai/ag2
  summary: A programming framework for agentic AI
  license: Apache-2.0
  license_file:
    - NOTICE.md
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
