schema_version: 1

context:
  name: pyautogen
  version: 0.10.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyautogen-${{ version }}.tar.gz
  sha256: ed42d7d94144d1333cc5727d904bf1c7a8deb8337b185adba332086997e4d682

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - hatchling
    - pip
  run:
    - autogen-agentchat >=0.6.4
    - anyio >=3.0.0,<5.0.0
    - httpx >=0.28.1,<1
    - fast-depends >=2.4.12,<3
    - asyncer ==0.0.8
    - websockets >=14,<15
    - python >=${{ python_min }},<3.13
    - openai >=1.58
    - diskcache
    - termcolor
    - flaml
    - numpy
    - python-dotenv
    - tiktoken
    - pydantic >=2.6.1,<3
    - docker-py
    - packaging

tests:
  - python:
      imports:
        - pyautogen
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: A programming framework for agentic AI
  license: Apache-2.0
  license_file: LICENSE-CODE
  homepage: https://github.com/ag2ai/ag2

extra:
  recipe-maintainers:
    - jan-janssen
